### ISSUE TITLE
Parrot 4.7 usage question

### ISSUE THREAD

**Issue by jordantsap** [Kid-X/Cleenux#1]
Why is it uninstalling some packages that are not uninstalled by the apt manager??
Maybe add a flag or builtin function for explaining things that take place in the procedure??

**Comment by kid-x** [comment]
The program removes **old config files, trashes and old kernels (optional)**. You have any new ideas, feel free to contribute.

**Comment by Kid-X** [comment]
This program clears unwanted files, old config files, trashes and etc. Anyway few mistakes were made in the code and the code has been fixed.
