### ISSUE TITLE
I'm Going to be Frank

### ISSUE THREAD

**Issue by terminalforlife** [Kid-X/Cleenux#3]
* Don't just suddenly clear all of the user's terminal text! You know some of that can be really important? Very important. If you must clear, use `tput` to save then restore the layout. (there are some good `tput` guides out there, or see how I've done it in my `shlides` shell program, in my Extra repository)

* Users have to pointlessly wait at _least_ 8 seconds because of the sleeps.

* You have `sudo` in the script, which is by many considered very bad practice. For one thing, the user might not even _have_ `sudo` available or installed. Some people just use `su` to get their root privileges. Not everyone goes running around a terminal as root in a penetration-testing distribution of Linux, like Kali. I recommend that you first test for the user having root access, and be mindful of what you have executing in the script.

* I recommend `printf` over `echo -e`; it's more direct, more portable, and far more functional. Just be sure to add a "\n" at the end, if you want the newline.

* You've gone for `apt-get clean` rather than the more respectful `autoclean` version. This means _all_ of the users cache (that kind at least) goes byebye. So if the user had a limited or very slow Internet connection, they're screwed; will have to re-download any pre-existing packages.

* `REMOVED ALL UNWANTED FILES, TRASHES AND TEMP FILES.` you say at the end. **You** consider them unwanted. You've given the user very little choice or control over what is _to them_ unwanted. Where's the warning?

* Perhaps the worst thing of all, is that it looks to me like the script will purge _all_ kernels but the user's current one. There goes the user's fallback kernel. You better hope they know how do that the advanced way. Anyone actually using that script is going to be very inexperienced, due to the simplicity of it. Meaning that the potential for this script to do something unwanted is very high. This is why Debian and typically what spawns from it, will remove all but **2** kernels, in order for the user to be left with a backup, in-case of things like kernel panic.

These things show a _complete_ disregard for the user and their setup, which is **not** good.

**Comment by Kid-X** [comment]
Thanks @terminalforlife for pointing out mistakes and suggesting changes. I changed most of the code and fixed almost everything that you've mentioned. Thank you again.
