### ISSUE TITLE
removing latest kernels while cleaning old kernels

### ISSUE THREAD

**Issue by muralikodali** [Kid-X/Cleenux#5]
i have tried latest version of cleenux.  while trying to clean the old kernels , it suggested to remove the latest kernel and install old kernel which is unwanted behaviour.

screenshot  is attached for reference.

![1577766517](https://user-images.githubusercontent.com/11482766/71610172-e0921880-2bb4-11ea-81ed-83f571a36513.png)

**Comment by Kid-X** [comment]
I fixed this issue. By the way, I fixed ["Issue 4"](https://github.com/Kid-X/Cleenux/issues/4) by editing the old script. I forgot to exclude the Kernel Removing part from the code. Thanks for reporting the issue.
